"""AI Match Analyst page."""
from __future__ import annotations

import streamlit as st

from _shared import require_model
from goalcast.llm.analyst import explain_prediction

predictor = require_model()
st.title("🤖 AI Match Analyst")
st.caption("Plain-English explanation grounded in the model's outputs and project docs.")

teams = predictor.teams
c1, c2, c3 = st.columns([2, 2, 1])
home = c1.selectbox("Home", teams, index=0)
away = c2.selectbox("Away", teams, index=1)
neutral = c3.checkbox("Neutral venue", value=True)

if home == away:
    st.info("Pick two different teams.")
    st.stop()

if st.button("Explain prediction", type="primary"):
    with st.spinner("Analysing..."):
        result = explain_prediction(predictor, home, away, neutral)
    st.markdown(f"> {result['explanation']}")
    st.caption(f"Generated by: {result['generated_by']}")

    with st.expander("Key drivers"):
        for d in result["drivers"]:
            st.markdown(f"- {d}")
    if result["sources"]:
        st.caption("Sources: " + ", ".join(result["sources"]))
